// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/proto/crud.proto

package mcrsv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoSetUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ProtoSetUser) Reset() {
	*x = ProtoSetUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_crud_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoSetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSetUser) ProtoMessage() {}

func (x *ProtoSetUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crud_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSetUser.ProtoReflect.Descriptor instead.
func (*ProtoSetUser) Descriptor() ([]byte, []int) {
	return file_api_proto_crud_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoSetUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProtoSetUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProtoSetUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ProtoUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx      int32  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserId   string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ProtoUser) Reset() {
	*x = ProtoUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_crud_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoUser) ProtoMessage() {}

func (x *ProtoUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crud_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoUser.ProtoReflect.Descriptor instead.
func (*ProtoUser) Descriptor() ([]byte, []int) {
	return file_api_proto_crud_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoUser) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *ProtoUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProtoUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProtoUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ProtoUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *ProtoUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ProtoUsers) Reset() {
	*x = ProtoUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_crud_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoUsers) ProtoMessage() {}

func (x *ProtoUsers) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crud_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoUsers.ProtoReflect.Descriptor instead.
func (*ProtoUsers) Descriptor() ([]byte, []int) {
	return file_api_proto_crud_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoUsers) GetUser() *ProtoUser {
	if x != nil {
		return x.User
	}
	return nil
}

type ProtoUserIdx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx int32 `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
}

func (x *ProtoUserIdx) Reset() {
	*x = ProtoUserIdx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_crud_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoUserIdx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoUserIdx) ProtoMessage() {}

func (x *ProtoUserIdx) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crud_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoUserIdx.ProtoReflect.Descriptor instead.
func (*ProtoUserIdx) Descriptor() ([]byte, []int) {
	return file_api_proto_crud_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoUserIdx) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type ProtoUpdateU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx      int32  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ProtoUpdateU) Reset() {
	*x = ProtoUpdateU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_crud_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoUpdateU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoUpdateU) ProtoMessage() {}

func (x *ProtoUpdateU) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crud_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoUpdateU.ProtoReflect.Descriptor instead.
func (*ProtoUpdateU) Descriptor() ([]byte, []int) {
	return file_api_proto_crud_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoUpdateU) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *ProtoUpdateU) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ProtoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res int32 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *ProtoResponse) Reset() {
	*x = ProtoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_crud_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoResponse) ProtoMessage() {}

func (x *ProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crud_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoResponse.ProtoReflect.Descriptor instead.
func (*ProtoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_crud_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoResponse) GetRes() int32 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_api_proto_crud_proto protoreflect.FileDescriptor

var file_api_proto_crud_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x75, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x63, 0x72, 0x73, 0x76, 0x22, 0x5f, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x6e,
	0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x32,
	0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x63, 0x72,
	0x73, 0x76, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x20, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x69, 0x64, 0x78, 0x22, 0x3c, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x21, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x32, 0x40, 0x0a, 0x06, 0x52, 0x70, 0x63, 0x41, 0x70, 0x70, 0x12,
	0x36, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x2e,
	0x6d, 0x63, 0x72, 0x73, 0x76, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x1a,
	0x14, 0x2e, 0x6d, 0x63, 0x72, 0x73, 0x76, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_crud_proto_rawDescOnce sync.Once
	file_api_proto_crud_proto_rawDescData = file_api_proto_crud_proto_rawDesc
)

func file_api_proto_crud_proto_rawDescGZIP() []byte {
	file_api_proto_crud_proto_rawDescOnce.Do(func() {
		file_api_proto_crud_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_crud_proto_rawDescData)
	})
	return file_api_proto_crud_proto_rawDescData
}

var file_api_proto_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_crud_proto_goTypes = []interface{}{
	(*ProtoSetUser)(nil),  // 0: mcrsv.ProtoSetUser
	(*ProtoUser)(nil),     // 1: mcrsv.ProtoUser
	(*ProtoUsers)(nil),    // 2: mcrsv.ProtoUsers
	(*ProtoUserIdx)(nil),  // 3: mcrsv.ProtoUserIdx
	(*ProtoUpdateU)(nil),  // 4: mcrsv.ProtoUpdateU
	(*ProtoResponse)(nil), // 5: mcrsv.ProtoResponse
}
var file_api_proto_crud_proto_depIdxs = []int32{
	1, // 0: mcrsv.ProtoUsers.user:type_name -> mcrsv.ProtoUser
	1, // 1: mcrsv.RpcApp.CreateUser:input_type -> mcrsv.ProtoUser
	5, // 2: mcrsv.RpcApp.CreateUser:output_type -> mcrsv.ProtoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_crud_proto_init() }
func file_api_proto_crud_proto_init() {
	if File_api_proto_crud_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_crud_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoSetUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_crud_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_crud_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_crud_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoUserIdx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_crud_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoUpdateU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_crud_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_crud_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_crud_proto_goTypes,
		DependencyIndexes: file_api_proto_crud_proto_depIdxs,
		MessageInfos:      file_api_proto_crud_proto_msgTypes,
	}.Build()
	File_api_proto_crud_proto = out.File
	file_api_proto_crud_proto_rawDesc = nil
	file_api_proto_crud_proto_goTypes = nil
	file_api_proto_crud_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RpcAppClient is the client API for RpcApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RpcAppClient interface {
	CreateUser(ctx context.Context, in *ProtoUser, opts ...grpc.CallOption) (*ProtoResponse, error)
}

type rpcAppClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcAppClient(cc grpc.ClientConnInterface) RpcAppClient {
	return &rpcAppClient{cc}
}

func (c *rpcAppClient) CreateUser(ctx context.Context, in *ProtoUser, opts ...grpc.CallOption) (*ProtoResponse, error) {
	out := new(ProtoResponse)
	err := c.cc.Invoke(ctx, "/mcrsv.RpcApp/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcAppServer is the server API for RpcApp service.
type RpcAppServer interface {
	CreateUser(context.Context, *ProtoUser) (*ProtoResponse, error)
}

// UnimplementedRpcAppServer can be embedded to have forward compatible implementations.
type UnimplementedRpcAppServer struct {
}

func (*UnimplementedRpcAppServer) CreateUser(context.Context, *ProtoUser) (*ProtoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterRpcAppServer(s *grpc.Server, srv RpcAppServer) {
	s.RegisterService(&_RpcApp_serviceDesc, srv)
}

func _RpcApp_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcAppServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcrsv.RpcApp/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcAppServer).CreateUser(ctx, req.(*ProtoUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _RpcApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mcrsv.RpcApp",
	HandlerType: (*RpcAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _RpcApp_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/crud.proto",
}
